# Generated by Django 4.1.4 on 2023-01-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidAmount', models.ImageField(max_length=10, upload_to='')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'paid',
                'verbose_name_plural': 'paids',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaryAmount', models.IntegerField(max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salarys',
            },
        ),
    ]
