# Generated by Django 4.1.4 on 2023-01-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='paidAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salaryAmount',
            field=models.IntegerField(),
        ),
    ]
