# Generated by Django 4.1.4 on 2023-01-02 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_paid_paidamount_alter_salary_salaryamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salary.salary'),
            preserve_default=False,
        ),
    ]
