# Generated by Django 4.1.4 on 2023-01-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_alter_paid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
