# Generated by Django 4.1.4 on 2023-01-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_paid_name_salary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='currsalaryAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
