# Generated by Django 4.1.4 on 2023-01-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_salary_currsalaryamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
