# Generated by Django 4.1.4 on 2023-01-11 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0007_alter_paid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SalaryPaids', to='salary.salary'),
        ),
    ]
